"""
Project: one row per video generation request (section 6 of PROJECT.md).
"""

import uuid
from typing import List, Optional

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.base import ProjectStatus, TimestampMixin, UUIDPKMixin


class Project(Base, UUIDPKMixin, TimestampMixin):
    __tablename__ = "projects"

    user_prompt: Mapped[str] = mapped_column(Text, nullable=False)

    title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    status: Mapped[ProjectStatus] = mapped_column(
        SAEnum(ProjectStatus, name="project_status", native_enum=False, length=32),
        default=ProjectStatus.CREATED,
        nullable=False,
        index=True,
    )

    language: Mapped[str] = mapped_column(String(16), default="en-US", nullable=False)
    target_audience: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    duration_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    video_path: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    thumbnail_path: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    captions_path: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)

    youtube_video_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    youtube_url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)

    # YouTube metadata generated by the LLM (section 14) — kept here rather than a
    # separate table since it's 1:1 with the project and always read/written together.
    youtube_title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    youtube_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    youtube_tags: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # comma-separated

    last_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    scenes: Mapped[List["Scene"]] = relationship(
        back_populates="project", cascade="all, delete-orphan", order_by="Scene.scene_number"
    )
    assets: Mapped[List["Asset"]] = relationship(back_populates="project", cascade="all, delete-orphan")
    jobs: Mapped[List["Job"]] = relationship(back_populates="project", cascade="all, delete-orphan")
    youtube_uploads: Mapped[List["YouTubeUpload"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    generation_logs: Mapped[List["GenerationLog"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Project id={self.id} status={self.status}>"
