"""add captions_path to projects

Revision ID: 387a1c5fa35f
Revises: dc2fa67093bd
Create Date: 2026-09-26 10:57:27.598267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387a1c5fa35f'
down_revision: Union[str, None] = 'dc2fa67093bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('captions_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'captions_path')
    # ### end Alembic commands ###
  