"""initial schema: projects, scenes, assets, jobs, youtube_uploads, generation_logs

Revision ID: dc2fa67093bd
Revises: 
Create Date: 2026-09-25 06:03:04.019559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2fa67093bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PLANNING', 'SCRIPT_GENERATED', 'SCENES_GENERATED', 'VISUALS_GENERATED', 'VOICE_GENERATED', 'CAPTIONS_GENERATED', 'RENDERING', 'READY_FOR_REVIEW', 'APPROVED', 'UPLOAD_STARTED', 'UPLOADING', 'UPLOADED', 'PUBLISHED', 'FAILED', name='project_status', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_title', sa.String(length=255), nullable=True),
    sa.Column('youtube_description', sa.Text(), nullable=True),
    sa.Column('youtube_tags', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('FULL_PIPELINE', 'SCRIPT_GENERATION', 'SCENE_REGENERATION', 'RENDER', 'YOUTUBE_UPLOAD', name='job_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_status', native_enum=False, length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('on_screen_text', sa.String(length=255), nullable=True),
    sa.Column('transition', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True),
    sa.Column('scene_video_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='scene_status', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_table('youtube_uploads',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('privacy_status', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='youtube_upload_status', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_uploads_project_id'), 'youtube_uploads', ['project_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.Enum('IMAGE', 'AUDIO_NARRATION', 'MUSIC', 'CAPTION_SRT', 'CAPTION_VTT', 'SCENE_VIDEO', 'FINAL_VIDEO', 'THUMBNAIL', name='asset_type', native_enum=False, length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_scene_id'), 'assets', ['scene_id'], unique=False)
    op.create_table('generation_logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='log_level', native_enum=False, length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_project_id'), 'generation_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_logs_scene_id'), 'generation_logs', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_logs_scene_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_project_id'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index(op.f('ix_assets_scene_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_youtube_uploads_project_id'), table_name='youtube_uploads')
    op.drop_table('youtube_uploads')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
